title: My Portfolio
description: Developer portfolio showcasing projects, skills and my contact information
theme: minima

header_pages:
  - index.md
  - about.md
  - projects.md
  - capstone.md
  - contact.md
